### ISSUE TITLE
admin - delete a keyword

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#884]
## Context
admins should be able to clear up the database and remove a keyword, including all instances of it currently in use

## user story
DELETE /api/v1/keywords/GUID
- [ ] admin only
- [ ] removes keyword from all annotations
- [ ] deletes keyword from database

## resources

![Image](https://github.com/WildMeOrg/houston/assets/62726866/7af7437f-c40a-4a68-be5e-eee4fba323fb)

**Comment by TanyaStere42** [comment]
needed for https://github.com/WildMeOrg/codex-frontend/issues/529

**Comment by naknomum** [comment]
the [code to do the api with keyword delete already exists](https://github.com/WildMeOrg/houston/blob/main/app/modules/keywords/resources.py#L123), however it does not work as expected

- right now, when you do `DELETE /api/keywords/GUID` you get an error, unless the keyword is not being used. this is due to the fact the db removal of the database (rightly) errors, since it is being referenced ("in use")
- i _think_ the solution might be to enable **cascade delete** on the _join table_ which combine: [Assets and Keywords](https://github.com/WildMeOrg/houston/blob/main/app/modules/assets/models.py#L27), as well as the one which [combine Annotation and Keywords](https://github.com/WildMeOrg/houston/blob/main/app/modules/annotations/models.py#L24)
- here is an [example](https://github.com/WildMeOrg/houston/blob/main/app/modules/auth/models.py#L79) of the code to define a cascade delete

i think it would be best to first just create a keyword (aka "tag") on an image (Asset). then do the API to delete it. you should see the error, which would look like below. then modify the table definition to allow the delete, and you should see the error go away and the keyword allowed to be deleted.

```
ERROR:  update or delete on table "keyword" violates foreign key constraint "fk_annotation_keywords_keyword_guid_keyword" on table "annotation_keywords"
DETAIL:  Key (guid)=(50e98d54-76e0-48c2-8899-53946b7c5b81) is still referenced from table "annotation_keywords".
```
